import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'WEB tutorials',
  description: 'Generated by rjk',
}

// children : page.js 파일의 리턴값
export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>
          {/* <a href='/'>WEB</a> */}
          <Link href='/'>WEB</Link>
        </h1>
        <ol>
          <li><Link href='/read/1'>HTML</Link></li>
          <li><Link href='/read/2'>CSS</Link></li>
        </ol>
        {children}
        <ul>
          <li><Link href='/create'>Create</Link></li>
          <li><Link href='/update'>Update</Link></li>
          <li><input type='button' value='Delete' /></li>
        </ul>
      </body>
    </html>
  )
}